### ISSUE TITLE
你这个能解决 node-sass 下载失败的问题吗？

### ISSUE THREAD

**Issue by lizyChy0329** [CreateWheel/mini-nrm#1]
希望有这样一条命令 `nrm use taobao -S node-sass cypress puppeteer`

**Comment by lete114** [comment]
这个想法不错👍

**Comment by lete114** [comment]
> 这个能解决 node-sass 下载失败的问题吗？

不能，因为 node-sass 在安装的时候自动执行[下载脚本](https://github.com/sass/node-sass/blob/ee13eb9c62449d1e535189a063cbdd15583ebf32/lib/extensions.js#L246)，因为它自己实现了一套下载程序，不受 npm 约束，所以 mini-nrm 无法解决此问题

**Comment by lete114** [comment]
你可以试试在安装 node-sass 后手动执行 `node node_modules/node-sass/scripts/install.js --sass-binary-site 自定义下载地址`

`cypress` 和 `puppeteer` 也同 `node-sass` 一样自己实现了一套自动下载脚本

**Comment by so1ve** [comment]
https://antfu.me/posts/npm-binary-mirrors
设置一下sass镜像就行

**Comment by lizyChy0329** [comment]
> https://antfu.me/posts/npm-binary-mirrors 设置一下sass镜像就行

get！其实我意思是能够在运行 nrm use taobao 时，同时将这些 binary-mirrors 也一同写入  .bashrc 或 .zshrc 里，就不用分两步走了

**Comment by lete114** [comment]
> get！其实我意思是能够在运行 nrm use taobao 时，同时将这些 binary-mirrors 也一同写入 .bashrc 或 .zshrc 里，就不用分两步走了

没法弄

1. 在 Windows 里没有 .bashrc 和 .zshrc 
2. 很难知道使用的是什么终端
3. 写入环境变量的话，会对用户的环境变量造成污染
4. 维护成本高，这些需要下载 binary 的包下载程序不统一，需要看源码或看文档才知道可以自定义下载镜像，而且环境变量名也不统一(如果都统一为`包名_binary_download`会好办一些)
5. binary-mirrors 比较少
