### ISSUE TITLE
node@20 运行报错

### ISSUE THREAD

**Issue by duowb** [CreateWheel/mini-nrm#3]
node 20
![image](https://github.com/user-attachments/assets/e9616851-b2be-42cf-b829-bc5141e5843b)

node 14
![image](https://github.com/user-attachments/assets/7d4cb0cf-7acc-4ec7-aebc-f601762b71af)

[解决方案](https://github.com/nodejs/node/issues/52554)

**Comment by lete114** [comment]
我这没问题啊

![image](https://github.com/user-attachments/assets/b564041a-05f9-4c3b-af7b-8c7d28cf4d14)

**Comment by duowb** [comment]
https://github.com/nodejs/node/issues/52554#issuecomment-2060019129

node@20.12.2出现的.

**Comment by lete114** [comment]
只在node@20.12.2中出现bug吗？如果是的话，我觉得没必要要去适配它

如果添加 `shell: true` 对其他nodejs版本没有影响的话，可以合并 (#4) 代码。你需要验证一下

**Comment by lete114** [comment]
我在node@20.12.2版本中使用mini-nrm并没有发生错误呀

![image](https://github.com/user-attachments/assets/acfdcf9e-ff16-4416-8674-f3a96087b4f4)

**Comment by duowb** [comment]
好的，可能是我的问题，我再看看吧~
